### ISSUE TITLE
Build failed with v4l2 feature

### ISSUE THREAD

**Issue by DmitrySamoylov** [raymanfx/libv4l-rs#1]
Hi,

I'm trying to include dependency using only `v4l2-sys`

```toml
v4l = { version = "0.5.0", features = [ "v4l2" ] }
```
but it fails:

```
fatal error: 'libv4l1.h' file not found
```

Yeah, I know, I can install it but why does it even need this header if I selected `v4l2` feature.

**Comment by DmitrySamoylov** [comment]
Alright, now it does not complain on missing `libv4l1.h`

```
v4l = { version = "0.5.0", default-features = false, features = [ "v4l2" ] }
```

but it still fails:

```
   |
52 |         request: ioctl::_IOC_TYPE,
   |                  ^^^^^ use of undeclared type or module `ioctl`
```

I think [here](https://github.com/raymanfx/libv4l-rs/blob/master/src/v4l2/api.rs#L52) is a typo: should be `vidioc` instead of `ioctl`

**Comment by raymanfx** [comment]
Good catch! That most definitely looks like a typo indeed. I'll push out a Bugfix release (0.5.1) tonight.

**Comment by raymanfx** [comment]
0.5.1 has just been published. Furthermore, I added an explicit CI build step with the v4l2 feature to prevent breakage in the future: https://github.com/raymanfx/libv4l-rs/commit/4fec71487701511f20fdd9c825cca96e9fb7d306.
