### ISSUE TITLE
Usage with cudaHostAlloc

### ISSUE THREAD

**Issue by htngr** [raymanfx/libv4l-rs#107]
I'm trying to use this library on a Nvidia jetson nano. My goal is to go directly from v4l2 to the jetson's GPU without going through the CPU (zero-copy). There are [official samples from nvidia](https://docs.nvidia.com/jetson/l4t-multimedia/l4t_mm_v4l2cuda.html) which accomplishes this with a Userptr to GPU / shared memory (allocated via cudaHostAlloc). How can I use this crate for this purpose? I couldn't find a way to pass a pointer to the UserptrStream.
An alternative could be DMA but it seems to me that this isn't implemented yet?

**Comment by molysgaard** [comment]
I have done exactly the same. See this for reference: https://github.com/raymanfx/libv4l-rs/pull/103
This is another sample point that allowing the user of the library to specify how memory is allocated should be supported :)

**Comment by htngr** [comment]
> I have done exactly the same. See this for reference: #103 This is another sample point that allowing the user of the library to specify how memory is allocated should be supported :)

Thanks, this seems to work (after writing a custom allocator)

**Comment by raymanfx** [comment]
dup: https://github.com/raymanfx/libv4l-rs/pull/103
