### ISSUE TITLE
`Format::new` not const fn

### ISSUE THREAD

**Issue by EtomicBomb** [raymanfx/libv4l-rs#17]
I would like to be able to define a nice `PREFERRED_FORMAT` constant for my project, but mine is ugly because I have to manually list all of the fields. Perhaps `v4l::Format::new` could be changed to
```rust 
const fn new(width: u32, height: u32, fourcc: FourCC) -> Self {
    Format {
        width,
        height,
        fourcc,
        field_order: FieldOrder::Any,
        stride: 0,
        size: 0,
        flags: Flags::empty(), // <- used to be Flags::from(0), which isn't const fn
        colorspace: Colorspace::Default,
        quantization: Quantization::Default,
        transfer: TransferFunction::Default,
    }
}
``` 
I think this change would make this library much more ergonomic.

**Comment by raymanfx** [comment]
Sure, why not. Please put up a pull request and let's take it from there.

**Comment by raymanfx** [comment]
Fixed by https://github.com/raymanfx/libv4l-rs/pull/20.
