### ISSUE TITLE
Feature: add support for Extended Controls (VIDIOC_S_EXT_CTRLS)

### ISSUE THREAD

**Issue by andresv** [raymanfx/libv4l-rs#39]
Currently [set_control](https://github.com/raymanfx/libv4l-rs/blob/master/src/device.rs#L206) uses `VIDIOC_S_CTRL` however sometimes it is also useful to use `VIDIOC_S_EXT_CTRLS `:
https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/extended-controls.html

**Comment by raymanfx** [comment]
Would you be willing to take a stab at the implementation? This functionality is not hugely important to me right now, so not sure when I would get time for it.

**Comment by andresv** [comment]
I can see that rscam https://github.com/loyd/rscam/blob/master/src/lib.rs#L495 only uses `VIDIOC_S_EXT_CTRLS`.
Maybe lets keep it as a placeholder for now.
