### ISSUE TITLE
Publish `next` to crates.io

### ISSUE THREAD

**Issue by D1plo1d** [raymanfx/libv4l-rs#65]
Would it be possible to publish the version in the `next` branch to crates.io?

I've been working on a simple h264 streaming crate based on this branch but I'm now blocked on publishing it until `next` goes live:

https://github.com/D1plo1d/h264_webcam_stream

**Comment by raymanfx** [comment]
Done!

**Comment by D1plo1d** [comment]
Thanks so much!
