### ISSUE TITLE
please release a new version of v4l2-sys-mit

### ISSUE THREAD

**Issue by yshui** [raymanfx/libv4l-rs#68]
the current version of v4l2-sys-mit on crates depends on bindgen 0.56, which in turns depends on `nom 5.1.2`, which triggers cargo's future incompatibility warning:

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
```

the version in the git repository doesn't have this problem.

**Comment by raymanfx** [comment]
Done, sorry for the long wait!
