### ISSUE TITLE
License is MIT?

### ISSUE THREAD

**Issue by laptou** [raymanfx/libv4l-rs#7]
I'm not sure if I'm misunderstanding how these licenses work, but this library is licensed under the MIT license, even though `libv4l` is LGPL. Is that correct? Does this mean that I can use this library without having to worry about the terms of the LGPL license (such as releasing my source code)?

**Comment by raymanfx** [comment]
As mentioned in the README [1], this crate does not depend on libv4l by default. Instead, it compiles against the v4l2.h Linux kernel header. If you choose the `libv4l-sys` feature and link against lib4l, you are under the obligations of that license. This crate being MIT licensed does not free you from that burden.

[1] https://github.com/raymanfx/libv4l-rs/blob/master/README.md#dependencies
