### ISSUE TITLE
OS Invalid input error

### ISSUE THREAD

**Issue by Necro-U** [raymanfx/libv4l-rs#97]
I am trying to execute [your example](https://github.com/raymanfx/libv4l-rs/blob/master/examples/stream_capture_userptr.rs) but i am getting this error:

Stream couldn't started: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }

I am using pop-os 22.04 and using droidcam as a camera.

**Comment by Necro-U** [comment]
Error does not appear on mmap capture example

**Comment by raymanfx** [comment]
That indicates the userptr buffer mechanism is not available for this hardware / driver combination. There's little we can do about that. Feel free to re-open if you think otherwise.

**Comment by devNat0** [comment]
I had the same error running `dev.format()` by wrongly importing `v4l::video::Output` instead of `v4l::video::Capture`.
